export const SHIPMENT_STATUS = {
  PENDING: 'PENDING',
  PICKED_UP: 'PICKED_UP',
  IN_TRANSIT: 'IN_TRANSIT',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  DELAYED: 'DELAYED'
};

export const STATUS_COLORS = {
  PENDING: '#FFA500',
  PICKED_UP: '#4169E1',
  IN_TRANSIT: '#1E90FF',
  OUT_FOR_DELIVERY: '#32CD32',
  DELIVERED: '#228B22',
  CANCELLED: '#DC143C',
  DELAYED: '#FF4500'
};

export const USER_ROLES = {
  ADMIN: 'ADMIN',
  EMPLOYEE: 'EMPLOYEE'
};

export const VIEW_MODES = {
  GRID: 'GRID',
  TILES: 'TILES'
};
